// src/main.zig — PRT-01 Integration Test: Zig calls Go bridge via C ABI.
//
// Run: zig build test
//
// Pass criteria (from PRT-01):
//   - Node count in buffer == 50,000
//   - No segfault (process exits 0)
//   - ArenaAllocator deinit() completes without crash
const std = @import("std");
const bridge = @cImport({
    @cInclude("bridge.h"); // Generated by `go build -buildmode=c-shared`
});

/// NodeRecord mirrors the C struct in bridge.h:
///   typedef struct { int32_t id, x, y, w, h; } NodeRecord;
const NodeRecord = extern struct {
    id: i32,
    x: i32,
    y: i32,
    w: i32,
    h: i32,
};

const NODE_COUNT: usize = 50_000;
const NODE_RECORD_SIZE: usize = @sizeOf(NodeRecord);

test "PRT-01: FFI bridge returns 50k nodes without segfault" {
    // Set up the Zig ArenaAllocator — sole owner of all memory during the call.
    var arena = std.heap.ArenaAllocator.init(std.heap.page_allocator);
    defer arena.deinit(); // O(1) free of everything allocated here.

    const allocator = arena.allocator();

    // Load the synthetic tfstate fixture embedded at compile time.
    // The fixture is generated by: go run ./cmd/gen-tfstate > testdata/fixture.tfstate.json
    const json_bytes = @embedFile("../testdata/fixture.tfstate.json");

    // Zig allocates the output buffer — this pointer crosses the FFI boundary.
    // Go must NOT retain any copy after ParseTFState returns.
    const buf = try allocator.alloc(NodeRecord, NODE_COUNT);

    // Call the Go-compiled C function.
    const written = bridge.ParseTFState(
        json_bytes.ptr,                      // *const i8 (null-terminated C string)
        @ptrCast(buf.ptr),                   // *anyopaque output buffer owned by Zig
        @intCast(NODE_COUNT),                // int32_t max capacity
    );

    // PRT-01 pass criteria ------------------------------------------------------
    try std.testing.expectEqual(@as(i32, NODE_COUNT), written);

    // Spot-check: node IDs should be sequential starting from 0.
    try std.testing.expectEqual(@as(i32, 0), buf[0].id);
    try std.testing.expectEqual(@as(i32, 1000), buf[1000].id);
    try std.testing.expectEqual(@as(i32, NODE_COUNT - 1), buf[NODE_COUNT - 1].id);

    // W and H should be within the generated bounds (50–249 and 30–129).
    for (buf) |node| {
        try std.testing.expect(node.w >= 50 and node.w < 250);
        try std.testing.expect(node.h >= 30 and node.h < 130);
    }

    // arena.deinit() is called via defer — no explicit free needed (PRT-01 O(1) cleanup).
}
